name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Yarn environment
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16

      - name: Build the extension
        run: yarn compile-production

      - name: Lint
        run: yarn lint

      - name: Install CMake/Ninja
        uses: lukka/get-cmake@v3.18.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build fake compilers
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          configure-options: -S ${{ runner.workspace }}/test/fakeOutputGenerator -DCMAKE_INSTALL_PREFIX:STRING=${{ runner.workspace }}/test/fakebin
          install-build: true

      - name: Delete NOTICE.txt
        run: del ${{ runner.workspace }}/NOTICE.txt

      - name: Run backend tests
        run: yarn backendTests

      - name: Run smoke tests
        run: yarn smokeTests

      - name: Run unit tests
        run: yarn unitTests

      - name: Run successful-build test
        run: yarn extensionTestsSuccessfulBuild

      - name: Run single root test
        run: yarn extensionTestsSingleRoot

      - name: Run multi root test
        run: yarn extensionTestsMultiRoot

      - name: Upload test logs if tests failed
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: TestLogs
          path: test/**/log.txt
          if-no-files-found: warn
